# Generated by Django 4.0.4 on 2022-04-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='time_slot',
            field=models.TimeField(null=True),
        ),
    ]
