# Generated by Django 4.0.4 on 2022-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_appointments_date_appointments_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='email'),
        ),
    ]
