# Generated by Django 4.0.4 on 2022-04-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('is_replied', models.BooleanField(default=False)),
            ],
        ),
    ]
