# Generated by Django 4.0.4 on 2022-05-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='date_time_fixed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
