# Generated by Django 4.0.4 on 2022-05-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='symptoms',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
