# Generated by Django 4.0.4 on 2022-05-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_consultation_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='fee',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='meet_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='registration_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
