# Generated by Django 4.0.4 on 2022-05-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_consultation_fee_consultation_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='fee',
            field=models.FloatField(default=250, null=True),
        ),
    ]
