# Generated by Django 4.0.4 on 2022-05-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total_amaount',
            new_name='total_amount',
        ),
    ]
