# Generated by Django 4.0.4 on 2022-05-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_rename_total_amaount_payment_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='consultation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='fee',
            field=models.FloatField(default=250),
        ),
    ]
