# Generated by Django 4.0.4 on 2022-06-25 14:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_consultation_consultation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
